### ISSUE TITLE
How to compute the rotation convective term?

### ISSUE THREAD

**Issue by BATDRAWER** [lesgo-jhu/lesgo#15]
The rotational form of the convective term is written as $u_j\left(\frac{\partial u_i}{\partial x_j}-\frac{\partial u_j}{\partial x_i}\right)+\frac{1}{2} \frac{\partial}{\partial x_i}\left(u_j u_j\right)$, I found the code for computing $u_j\left(\frac{\partial u_i}{\partial x_j}-\frac{\partial u_j}{\partial x_i}\right)$ in convec.f90, yet the rest of the convective term, i.e., $\frac{1}{2} \frac{\partial}{\partial x_i}\left(u_j u_j\right)$ is missing, why is that?

**Comment by jbret** [comment]
You are correct. That missing term is the gradient of resolved kinetic energy and it is combined with the pressure gradient, so it is appropriate for it to be missing here.
