### ISSUE TITLE
Standard Smagorinsky Model

### ISSUE THREAD

**Issue by RUBEL-CHANDRA-DAS** [lesgo-jhu/lesgo#5]
Hi,

In the Standard Smagorinsky Model implementation, has the Co(or Cs, the Smagorinsky Constant) value been included twice?

Here are two lines from sgs_stag_util.f90:
On line 130,
                l(1) = ( Co**(wall_damp_exp)*(vonk*zz(1))**(-wall_damp_exp)&
                    + (delta)**(-wall_damp_exp) )**(-1._rprec/wall_damp_exp)
On line 234,
    Nu_t(jx,jy,jz) = S(jx,jy)*Cs_opt2(jx,jy,jz)*l(jz)**2

You can see that the Co already been used in l(1) calculation, so only for the Standard Smagorinsky Model implementation, you do not need to include it again in the calculation of Nu_t(jx,jy,jz). FYI, for the other models, line 234 is alright.

Please let me know if I'm wrong. 

Thanks,
Rubel.

**Comment by crshapiro** [comment]
Hi Rubel,

Thanks for your question. Line 130 comes from the Mason wall damping:
(Cs\Delta)^{-n} = (Co \Delta)^{-n} + (kz)^{-n}
\nu_T = (Cs\Delta)^2 |S|
See https://lesgo.me.jhu.edu/subgrid.html for more details. 

The code isn't written exactly as I wrote the equations, but that's what it's doing.

Hope that helps,
Carl
